services:

  mongo:
    build: mongodb/
    environment:
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: pswd
      MONGO_INITDB_DATABASE: recipe-management
    volumes:
      - ./mongodb:/data/db
    ports:
      - "27017:27017"

  backend:
    build: backend/
    ports: 
      - "8000:8000"
    volumes: 
      - ../Hack4Earth:/recipe-app/
    depends_on:
      - mongo

  frontend:
    build: frontend/
    ports:
      - "3000:3000"
    volumes:
      - ../Hack4Earth:/recipe-app/
    depends_on:
      - backend